#!# perl: argos/code/m.http
use strict;
use LWP::UserAgent;

use Vulcan::Grep;

our %PARAM =
(
    timeout => 10, port => 80, code => [ 200 ],
    grep => [], uri => '/', proto => 'http',
);

our %ERROR =
(
    down => 'web service down', null => 'no content',
    cont => 'invalid response', code => 'invalid code',
);

return sub
{
    my ( %param, %mesg ) = @_;
    my ( $batch, $param ) = @param{ qw( batch param ) };
    my ( $proto, $port, $uri, $code, $grep, $timeout ) = map
        { $param->{$_} || $PARAM{$_} } qw( proto port uri code grep timeout );

    map { $_ = [ $_ ] if ref $_ ne 'ARRAY' } $code, $grep;

    my $ua = LWP::UserAgent->new();

    $ua->timeout( $timeout );
    $ua->env_proxy;

    for my $node ( @$batch )
    {  
        $node .= ":$port" if $node !~ /:\d+$/;

        my $url = "$proto://$port$uri";
        my $re = $ua->get( $url );
        my $rc = $re->code();

        my $err = ( ! $re->is_success() ) ? 'down'
            : ( ! grep { $_ == $rc } @$code ) ? 'code'
            : ( ! @$grep ) ? next
            : ( ! ( $url = $re->decoded_content() ) ) ? 'null'
            : ( ! @{ Vulcan::Grep->new( input => $url, rule => $grep )->eval } )
            ? 'cont' : next;

        push @{ $mesg{error}{ $ERROR{$err} } }, $node;
    }

    return \%mesg;
};

