#!/usr/bin/env perl

use strict;
use warnings;

use Dancer;
use File::Spec;

use Vulcan::OptConf;

$| ++;

my %seco; BEGIN { %seco = Vulcan::OptConf->load()->dump( 'seco' ) }

use lib $seco{lib};
use SECO::Conf;

get "/seconfig/:cluster" => sub
{
    my ( $output, $i ) = ( '', 0 );
    for my $cluster ( split ',', params()->{cluster} )
    {
        next unless my ( $conf, $replica ) = loadconf( $cluster );
        map { $output .= join( ':', @$_, ++ $i ) . "\n" }
            $conf->dump( seco => $replica );
    }
    return $output;
};

dance;

sub loadconf
{
    my $domain = $SECO::DOMAIN;
    my $conf = shift; $conf =~ s/$domain$//;

    return () unless $conf =~ s/(\d+)@/@/;
    eval { $conf = SECO::Conf->load( File::Spec->join( $seco{conf}, $conf ) ) };
    return $@ ? () : ( $conf, $1 );
}
