#!/usr/bin/env perl

use strict;
use warnings;

use YAML::XS;
use File::Spec;

use Vulcan::OptConf;

$| ++;

my %seco; BEGIN { %seco = Vulcan::OptConf->load()->dump( 'seco' ) }

use lib $seco{lib};
use SECO::ExpSSH;

my $user = `logname`; chomp $user;
my $pass = File::Spec->join( ( getpwnam $user )[7], '.go' );

splice @ARGV, 1, 0, each %{ YAML::XS::LoadFile $pass };
die "cannot resolve host\n" unless SECO::ExpSSH->new->conn( @ARGV );
