#!/usr/bin/env perl

use strict;
use warnings;

use Vulcan::Sudo;
use Vulcan::OptConf;

my %seco;

BEGIN
{
    Vulcan::Sudo->sudo( 'search' );
    $Vulcan::OptConf::THIS = 'seco';
    %seco = Vulcan::OptConf->load()->get( qw( daemon interval=i ) )->dump();
}

use lib $seco{lib};
use SECO::Index;

$seco{interval} ||= 5;
do { SECO::Index->new()->run() } while $seco{daemon} && sleep $seco{interval};
exit 0;
