#!/usr/bin/perl -w

=head1 SYNOPSIS

Covert hermes databases to hermes cache

=cut
use strict;

use Hermes::Cache;
use Vulcan::OptConf;

$| ++;

$Vulcan::OptConf::THIS = 'hermes';

my %o = Vulcan::OptConf->load()->get( qw( daemon interval=i ) )->dump();
my ( $daemon, $interval ) = delete @o{ qw( daemon interval ) };

$interval ||= 5;

do { Hermes::Cache->new( %o )->make } while $daemon && sleep $interval;

exit 0;
